---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.5
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_trivy
        args:
          - --args=--config=configs/trivy.yaml

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.457
    hooks:
      - id: checkov
        args: [--config-file, ./configs/checkov.yml]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - ./configs/.secrets.baseline

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.20.0"
    hooks:
      - id: terraform-docs-go
        name: terraform-docs (module)
        language_version: "1.24.6"
        args:
          - "markdown"
          - "table"
          - "--output-file"
          - "README.md"
          - "."

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix, --config=./configs/ruff.toml]
      - id: ruff-format
        args: [--config=./configs/ruff.toml]
